apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard-controller-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              memory: 200Mi
