apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#resources:
#- https://github.com/kubeflow/kfserving-lts/tree/b00db4bc24b9ad63e0f5c89ad41437cf32d7b4a8/config/overlays/kubeflow

# Adds namespace to all resources.
namespace: kubeflow

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
- ./default

generatorOptions:
  disableNameSuffixHash: true

# To make namespace for standalone installation kustomizable,
# variabalize ingress gateway, webhook service name and
# kfserving namespace in webhook configurations
configMapGenerator:
  - name: kfserving-config
    behavior: replace
    envs: 
    - params.env


images:
- name: kfserving/kfserving-controller
  newName: kfserving/kfserving-controller
  newTag: v0.5.0-rc0
  # digest: sha256:321f35c2cd934d449f9e1308ca45a8c9a92190bec83a33b37a18a6b4b649506a
