apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- https://github.com/kubeflow/kfserving-lts/tree/v0.5.0-rc0/config/overlays/kubeflow
- https://github.com/checomp/kfserving-lts/tree/release-0.6/config/overlays/kubeflow

images:
- name: kfserving/kfserving-controller
  newName: kfserving/kfserving-controller
  newTag: v0.5.0-rc0
  # digest: sha256:321f35c2cd934d449f9e1308ca45a8c9a92190bec83a33b37a18a6b4b649506a
