apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kserve/kserve/config/overlays/kubeflow

images:
- name: kserve/kserve-controller
  newName: kserve/kserve-controller
  newTag: v0.13.1
  # digest: sha256:321f35c2cd934d449f9e1308ca45a8c9a92190bec83a33b37a18a6b4b649506a
