apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ulissigroup/argoflow.git
    targetRevision: HEAD
    path: kubeflow/notebooks/notebook-controller
    kustomize:
      version: v4.2.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
