apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "qvOD6OS1skOYmjb7hHhDwym/Kk1rDMnMBNZpzCy6eWzXJZFsVTBKqx4p1r1buH4G\nU9ScIXfUsnXSTY/dtcWJEO5vFaTjeflyzr+tMlPwsx6YxIUZG4B6tZvCEC5FwPiC\nH5s2gpbhxmPp88/49yarW/N4SA3TgcVa49V6yIc+3Js="
